name: Build

on: [push]

jobs:
  build:
    name: Build on ${{ matrix.os }} with node ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: ["16"]
        go-version: ["1.16"]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: ./build_all.bat
        if: ${{ matrix.os == 'windows-latest' }}
      - run: ./build_all.sh
        if: ${{ matrix.os != 'windows-latest' }}
      - uses: actions/upload-artifact@v3
        with:
          name: le-lan-launcher-node${{ matrix.node-version }}-${{ matrix.os }}
          path: |
            dist_electron
            syncthing
            syncthing.service.example